blueprint:
  name: Motion-activated lights with night mode
  description: Turn on lights when motion is detected, with a night mode option.
  domain: automation
  input:
    # Trigger Inputs
    trigger:
      name: Trigger *
      icon: mdi:cog-outline
      collapsed: true
      input:
        motion_sensor:
          name: Motion Sensor
          description: The motion sensor that triggers the lights.
          default: []
          selector:
            entity:
              filter:
              - domain:
                - binary_sensor
                - schedule
              multiple: true
    light_settings:
      name: Lichter *
      icon: mdi:lightbulb-outline
      collapsed: true
      input:
        light_duration:
          name: Light Duration
          description: Duration for which the lights should stay on.
          default: 5
          selector:
            number:
              min: 0.0
              max: 30.0
              step: 0.5
              unit_of_measurement: minutes
              mode: slider
        on_lights:
          name: Lights
          description: The lights to turn on.
          selector:
            entity:
              domain: light
        transition:
          name: Transition Time
          description: Transition time for turning on/off the lights (in seconds).
          default: 1
          selector:
            number:
              min: 0.0
              max: 5.0
              step: 0.1
              unit_of_measurement: seconds
        transition_off:
          name: Transition Time Off
          description: Transition time for turning off the lights (in seconds).
          default: 1
          selector:
            number:
              min: 0.0
              max: 5.0
              step: 0.1
              unit_of_measurement: seconds
        brightness_day:
          name: Day Brightness
          description: Brightness level of the lights during the day (0-255).
          default: 255
          selector:
            number:
              min: 1.0
              max: 100.0
              step: 1.0
              unit_of_measurement: '%'
        color_temp_day:
          name: Day Color Temperature
          description: Color temperature of the lights during the day (in Kelvin).
          default: 2500
          selector:
            number:
              min: 2000.0
              max: 8000.0
              step: 100.0
              unit_of_measurement: kelvin
    night_light_settings:
      name: Nachtlicht Settings
      icon: mdi:weather-night
      collapsed: true
      input:
        use_night_settings:
          name: Use Night Settings
          description: Use night settings for the lights.
          default: false
          selector:
            boolean: {}
        night_light_start:
          name: Night Light Start Time
          description: Start time for night lights.
          default: "22:00:00"
          selector:
              time: {}
        night_light_end:
          name: Night Light End Time
          description: End time for night lights.
          default: "06:00:00"
          selector:
              time: {}
        brightness_night:
          name: Night Brightness
          description: Brightness level of the lights during the night (0-255).
          default: 100
          selector:
            number:
              min: 0.0
              max: 100.0
              step: 1.0
              unit_of_measurement: '%'
        color_temp_night:
          name: Night Color Temperature
          description: Color temperature of the lights during the night (in Kelvin).
          default: 2500
          selector:
            number:
              min: 2000
              max: 8000
              step: 100.0
              unit_of_measurement: kelvin
mode: restart
max_exceeded: silent
trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "on"
    id: t_on
  - platform: time
    at: !input night_light_start
    id: t_night_start
  - platform: time
    at: !input night_light_end
    id: t_night_end

action:
  - choose:
      - conditions:
          - condition: time
            after: !input night_light_start
            before: !input night_light_end
          - condition: or
            conditions:
              - condition: state
                entity_id: !input on_lights
                state: "on"
              - condition: trigger
                id: t_on
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input on_lights
            data:
              brightness: !input brightness_night
              kelvin: !input color_temp_night
              transition: !input transition
    default:
      - service: light.turn_on
        target:
          entity_id: !input on_lights
        data:
          brightness: !input brightness_day
          kelvin: !input color_temp_day
          transition: !input transition
  - delay:
      minutes: !input light_duration
  - service: light.turn_off
    target:
      entity_id: !input on_lights
    data:
      transition: !input transition_off
